export const GROCERY_STORES = [
  'No Frills',
  'Sobeys',
  'Longo\'s',
  'Walmart',
  'Metro',
  'FreshCo',
  'Costco',
  'Real Canadian Superstore',
  'Loblaws',
  'Farm Boy',
  'Sunny Supermarket',
  'WinCo Food Mart',
  'Galleria Supermarket',
  'H Mart',
  'Bestco Food Mart',
  'Foody',
  'T&T Supermarket',
];
